---
abstract: 'UserLogin plugin suppliment for changing user passwords'
author:
  - "'Zoffix <'zoffix@cpan.org'>"
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-UserLogin-ChangePassword
provides:
  App::ZofCMS::Plugin::UserLogin::ChangePassword:
    file: lib/App/ZofCMS/Plugin/UserLogin/ChangePassword.pm
    version: 0.0110
requires:
  App::ZofCMS::Plugin::Base: 0.0105
  DBI: 1.607
  Digest::MD5: 2.36_01
  HTML::Template: 2.9
resources:
  license: http://dev.perl.org/licenses/
version: 0.0110
